data_path: "data/"
output_dir: "models_checkpoints/"

name: "unet_resnet26"

device: "cuda"

folds:
    n_splits: 4
    random_state: 808
    bins: 20

train_folds: [0, 1, 2, 3]
fold_strategy: random
    
seed: 808

debug: 1

train_bs: 8
valid_bs: 128
num_workers: 1

num_epochs: 20
image_size: 384

save_path: "models_checkpoints/"
save_strategy: "epoch"
save_period: 1

early_stop:
    monitor: "val_loss"
    patience: 999

synthetic:
    enable: False
    num_epochs: 20
    once: True

augmentations:
    enable: True
    set: 3

seg_model: "Unet"
encoder_name: "timm-efficientnet-b0"

loss_smooth: 1.e-7

optimizer_params:
    lr: 0.0005
    weight_decay: 0.0

scheduler:
    name: "cosine_with_hard_restarts_schedule_with_warmup"
    params:
        cosine_with_hard_restarts_schedule_with_warmup:
            num_warmup_steps: 350
            num_training_steps: 3150
            num_cycles: 1