data_path: "data/"
output_dir: "models_checkpoints/"

name: "unet_efb5_noisy_512"

device: "cuda"

debug: 0

fold_strategy: "mask_size"
train_class: True

folds:
    n_splits: 4
    random_state: 808
    bins: 20

train_folds: [0,1,2,3]

add_pseudo: False
frames_list: [2, 3, 5, 6] 
    
seed: 808

train_bs: 32
valid_bs: 128
num_workers: 1

num_epochs: 30
image_size: 512

save_path: "models_checkpoints/"
save_strategy: "best"
save_period: 1

early_stop:
    monitor: "val_loss"
    patience: 999

seg_model: "Unet"
encoder_name: "timm-efficientnet-b5"
encoder_depth: 5
encoder_weights: "noisy-student"

loss_smooth: 1.E-7

optimizer_params:
    lr: 0.0005
    weight_decay: 0.0

scheduler:
    use: 1
    name: "cosine_with_hard_restarts_schedule_with_warmup"
    params:
        cosine_with_hard_restarts_schedule_with_warmup:
            num_warmup_steps: 350
            num_training_steps: 3150
            num_cycles: 1