data_path: "data/"
output_dir: "models_checkpoints/"

name: "unet_resnet26"

device: "cuda"

folds:
    n_splits: 4
    random_state: 808

train_folds: [0, 1, 2, 3]
    
seed: 808

train_bs: 64
valid_bs: 128
workers: 1

num_epochs: 20
image_size: 384

save_path: "models_checkpoints/"
save_strategy: "epoch"
save_period: 1

early_stop:
    monitor: "val_loss"
    patience: 999

model:
    seg_model: "Unet"
    encoder_name: "timm-resnest26d"

loss_smooth: 1e-7

optimizer_params:
    lr: 0.0005
    weight_decay: 0.0

scheduler:
    name: "cosine_with_hard_restarts_schedule_with_warmup"
    params:
        cosine_with_hard_restarts_schedule_with_warmup:
            num_warmup_steps: 350
            num_training_steps: 3150
            num_cycles: 1